### ISSUE TITLE
Unable to connect to sample OData feed 

### ISSUE THREAD

**Issue by SteveLasker** [OData/lab#10]
Tried: http://services.odata.org/v4/TripPinServiceRW/http://services.odata.org/v4/TripPinServiceRW/
![odatasamplefeed](https://cloud.githubusercontent.com/assets/7647382/8236707/0296678c-159f-11e5-99ce-cc7dbc002ff1.png)

**Comment by congysu** [comment]
Thanks @SteveLasker.  We track the issue in Support Code Gen for OData V4 #21.
