### ISSUE TITLE
Adding OData Connected Service to the project failed: Could not get CLR type name for EDM type 'Edm.PropertyPath'

### ISSUE THREAD

**Issue by Tiberriver256** [OData/lab#110]
Hey,

We're getting an error when generating a client from an OData v4.01 service and getting the above error. Do we perhaps need to update the Microsoft.OData.Edm dependency?

Adding OData Connected Service to the project failed: Could not get CLR type name for EDM type 'Edm.PropertyPath'

**Comment by unchase** [comment]
Hi, @Tiberriver256 
You can try to use the lastest version of the [ODataConnectedService](https://github.com/OData/ODataConnectedService).

**Comment by Tiberriver256** [comment]
Thanks @unchase!
This was using 0.11.1 but I hadn't realized the repo had moved. I'll close this out and reopen it in the main.
