### ISSUE TITLE
ProviderId should be consistent with other Microsoft ProviderIds

### ISSUE THREAD

**Issue by SteveLasker** [OData/lab#13]
To be consistent with Connected Service Provider naming, and to align with the Microsoft specific providers, can you please name your ProviderId Microsoft.OData
Here’s an example of other Provider Ids

Datalogics.PDF.Web
Microsoft.Azure.AD
Microsoft.Azure.MobileServices
Microsoft.Azure.Storage
Microsoft.Office365
Microsoft.Samples.VSOnline
Microsoft.ApplicationInsights
Salesforce.ForceDotCom

**Comment by LaylaLiu** [comment]
I changed it Microsoft.OData.ConnectedService by https://github.com/OData/lab/commit/fd469e81221a49c8fa6f08e48e849205ab075566
