### ISSUE TITLE
Generated swagger not passing validation

### ISSUE THREAD

**Issue by brandon-irl** [OData/lab#25]
Using the ODATAServiceToSwagger tool with the swagger.io validator (_http://online.swagger.io/validator/debug?url={YOUR.swagger.json}_) will fail validation. Example response:
`
[
  {
    "level": "error",
    "domain": "validation",
    "keyword": "oneOf",
    "message": "instance failed to match exactly one schema (matched 0 out of 2)",
    "schema": {
      "loadingURI": "http://swagger.io/v2/schema.json#",
      "pointer": "/definitions/parametersList/items"
    },
    "instance": {
      "pointer": "/paths/~1AlertTemplates({AlertActionId})/get/parameters/0"
    }
  }
]`

In particular, this is due to missing the "required" property for pathParameterSubSchema objects

**Comment by robward-ms** [comment]
Merged.
