### ISSUE TITLE
Add license header for source files

### ISSUE THREAD

**Issue by congysu** [OData/lab#28]
Such as:

``` c#
// Copyright (c) Microsoft Corporation.  All rights reserved.
// Licensed under the MIT License.  See License.txt in the project root for license information.
```

**Comment by LaylaLiu** [comment]
There is an extension tool ( https://visualstudiogallery.msdn.microsoft.com/5647a099-77c9-4a49-91c3-94001828e99e) in VS which can help to add license headers

**Comment by TomDu** [comment]
Merged, thanks.

**Comment by EMMWIS** [comment]
> Such as:
> 
> ```cs
> // Copyright (c) Microsoft Corporation.  All rights reserved.
> // Licensed under the MIT License.  See License.txt in the project root for license information.
> ```

c0rey.be.side.be
