### ISSUE TITLE
DefaultContainer?

### ISSUE THREAD

**Issue by KevinBurton** [OData/lab#38]
In the CRUD documentation I see a deference to the DefaultContainer. I am not sure where that is located. I cannot find it.

**Comment by lgadola** [comment]
same here, can't find a DefaultContainer

**Comment by chinadragon0515** [comment]
If you use client code gen to generate the code, the class name of Container is same from the name in metadata, like for this sample case,

http://services.odata.org/V4/(S(v4sy5odkmnqt3e2xt0njhyvf))/TripPinServiceRW/$metadata

we can see "<EntityContainer Name="DefaultContainer">", so the generate class name will be DefaultContainer, but if your metadata has different name like Container, then the generate class name will be Container.

Check your metadata to see the name of EntityContainer, that will be your container class name.

BTW, this project is not actively monitor, and for CRUD document, it is related to odata.net project, open issues https://github.com/OData/odata.net for issue related to odata .net.
And we recommend to ask questions in stackoverflow where whole community can help.

**Comment by chinadragon0515** [comment]
As it is not an issue, close the issue.

**Comment by dieterwiesflecker** [comment]
Even as non-issue it helped!

**Comment by MKaranusic** [comment]
Super helpful 👍
