### ISSUE TITLE
Sample Use HttpClient in OData Client

### ISSUE THREAD

**Issue by battermaster** [OData/lab#43]
The sample Use HttpClient in OData Client in Link http://odata.github.io/odata.net/#04-10-use-httpclient-in-odata-client  has problem now?
The samle get no data from server.

**Comment by LaylaLiu** [comment]
It seems to be a document related issue or a client issue about the client hooks, please open a Github issue in OData/odata.net. I will just close this one.

**Comment by HakimLado** [comment]
Has this issue been addressed? If so, can somebody point me to the solution?
