### ISSUE TITLE
No longer appears in list after update3

### ISSUE THREAD

**Issue by stewartbasterash** [OData/lab#47]
I was using this scaffolding for a number of projects I was working on and now after update 3 it no longer appears in the list of "add controller".

**Comment by chinadragon0515** [comment]
@stewartbasterash this is not a project been actively monitored now.

If you are using Web Api OData scaffolding, please open issue in https://github.com/OData/WebApi

If you are using Odata .net client scaffolding, please open issue in https://github.com/OData/odata.net

If you are using restier scaffolding, please open issue in https://github.com/OData/RESTier/

I close this issue.
