### ISSUE TITLE
Connecting Through Http Proxy Server

### ISSUE THREAD

**Issue by ghost** [OData/lab#50]
I have deployed a client application on an environment that requires all connections to be made through a specific http proxy server. How to pass that proxy server details to the OData Client Container?

**Comment by unchase** [comment]
You can try [Unchase OData ConnectedService](https://marketplace.visualstudio.com/items?itemName=Unchase.unchaseodataconnectedservice) for solve this problem. The service supports web-proxy with credentials.

**Comment by mumbi-o** [comment]
Closing this issue as it is fixed in the new ODATA Connected service,
