### ISSUE TITLE
Need version for VS2017

### ISSUE THREAD

**Issue by Mech0z** [OData/lab#51]
Any plans for supporting VS 2017 ? I tried opening the Vsix and changing to version 15, but that didnt work

**Comment by fileman** [comment]
Hi, I've [forked](https://github.com/fileman/lab/tree/master/ODataConnectedService) this repo and updated references and the vsixmanifest and now I can install and run in VS2017, but only for ODataV4.
Waiting official release of this extension and RESTier stable.
Use at your own risk and possible license violation.

**Comment by robsiera** [comment]
@fileman, your ODataV4-only was a showstopper for me. Hence [my fork](https://github.com/robsiera/lab/tree/master/ODataConnectedService) which still supports v1-v4.  Thanks for showing me the road.  Couldn't have done it as fast without your fork as an example.

**Comment by fileman** [comment]
The beauty of open source, thanks @robsiera 
Since your fork supports OData V1-V4, make a PR to main branch!

**Comment by Mech0z** [comment]
@robsiera I still get http://i.imgur.com/9Tn75KZ.png when I try to "Update service reference" in VS2017 if I compile your version, is there something else that needs to be changed for that to work?

**Comment by robsiera** [comment]
@Mech0z You compiled the code in Release build? You uninstalled any previously installed vsix of Microsoft.OData.ConnectedService? You installed the \ODataConnectedService\src\bin\Release\Microsoft.OData.ConnectedService.vsix ?

Here my [Release](https://github.com/OData/lab/files/929944/Release.zip) files

**Comment by Mech0z** [comment]
@robsiera Tried your release file, uninstalled my own and installed that one, but still gets the same error. Is there a log printed somewhere with a more detailed error?

**Comment by robsiera** [comment]
@Mech0z Did you follow the instructions "Generate Client Proxy" at the end of [this page](http://odata.github.io/odata.net/#OData-Client-Code-Generation-Tool)?

**Comment by Mech0z** [comment]
@robsiera Ah my bad, I thought I could reuse my existing Service reference and just do "update service reference" but if I added it as a Connected service instead it worked fine. Is there any major difference between the 2 types?

**Comment by robsiera** [comment]
no difference at all.

**Comment by Mech0z** [comment]
@robsiera Okay, could hope for better git merge support :) we always gets merge conflicts if one person have added 1 property or class to the reference

**Comment by aferreira44** [comment]
Thanks for the VS 2017 version but I get this error ([https://snag.gy/tSZWjU.jpg](https://snag.gy/tSZWjU.jpg)) when I try update my old connected service or create a new one. Any idea to solve this?

**Comment by estiller** [comment]
Wow, it's July already and the PR is still not merged in yet?
https://github.com/OData/lab/pull/53

@robsiera Thanks for your work! I managed to install it successfully in VS2017.

**Comment by ghost** [comment]
@aferreira44 I forked @robsiera code and fixed this issue. It was because the v3codegen had a dependency on the WCF Data Services been installed.

Here is the [blame](https://github.com/martinholden-skillsoft/lab/commit/b45340c5cb228824ba58b6bb586248ef1aa95ae2#diff-7495e425b287a98adf82b9d4343951e6)

**Comment by nla-brandonjames** [comment]
@martinholden-skillsoft This is great! I don't know how to build this project but I do get the same error when I use the extension, trying to access data from the official OData sample server. I was hoping that if I ever got the SAP OData server we have on site working this would still happen. By the way, would you know how to fix this error of mine? https://github.com/OData/lab/issues/56. I don't know if it has something to do with an invalid ssl cert or not. I can't find where in the code the message is generated from.

**Comment by nla-brandonjames** [comment]
Alright, I did build and install this solution, and I got one step closer to generating the code, but I got stuck with a new error.

![Screenshot](http://i.imgur.com/JRBVPpN.png)

Even after I manually remove these from a file, it still gives me issues with things not being defined in the namespace...

**Comment by AlanWong-MS** [comment]
![image](https://user-images.githubusercontent.com/22382722/29632623-66a80db6-87f8-11e7-9e28-1bc70c8966b1.png)

Hi everyone, we've been busy with transitions, ramp-ups, and housecleaning during the past months, and now, we're going to work on this. Thanks for your patience!

**Comment by AlanWong-MS** [comment]
I reviewed @robsiera's PR #53 and it installed fine on my VS2017. I'll be consolidating issues via that PR. Please feel free to add input there.

**Comment by AlanWong-MS** [comment]
Addressed with PR #62! Please take a look at the [Marketplace](https://marketplace.visualstudio.com/items?itemName=laylaliu.ODataConnectedService) for the updated extension that should now support VS2017. Thank you for your support!
