### ISSUE TITLE
OData URL Textbox

### ISSUE THREAD

**Issue by SteveLasker** [OData/lab#7]
- The OData URL textbox needs to be full width, to allow for normal OData URLs
- The OData URL should support MRUs, to help the developer with previously entered values
  https://github.com/developerforce/visual-studio-tools/blob/master/src/Salesforce.VisualStudio.Services/ConnectedService/ViewModels/DesignTimeAuthenticationViewModel.cs
  ![odataurltextbox](https://cloud.githubusercontent.com/assets/7647382/8236061/aeba4ef2-159a-11e5-8196-7791a9a1174d.png)

**Comment by LaylaLiu** [comment]
Fixed by https://github.com/OData/lab/commit/fd469e81221a49c8fa6f08e48e849205ab075566
