### ISSUE TITLE
The connection to the Odata Endpoint should work with Credentials

### ISSUE THREAD

**Issue by klacol** [OData/lab#72]
The VSIX for the OData Connected Service can be downloaded and installed in Visual Studio 2017 from here:

https://marketplace.visualstudio.com/items?itemName=laylaliu.ODataConnectedService

Then one can add an OData Connected Service. 

When you put in the URL the an Endpoint, that is secured with basic authentication and HTTPS this message is shown:

"Cannot Access"

The connection to the Odata Endpoint should work with Credentials.

**Comment by Gabee01** [comment]
I think it's related to #56

**Comment by klacol** [comment]
Will Odata work with VS 2017 at some time or is it discontinued?

**Comment by klacol** [comment]
Duplicate to #56

Can still not use Odata in VS 2017 with secured endpoints.
