### ISSUE TITLE
Unable to Connect to secure End Point - Custom Headers

### ISSUE THREAD

**Issue by kdcllc** [OData/lab#73]
I have VS2017 v.15.3.5 and it works for non-secure connections but we have a secure end point that requires as to pass custom headers for authentication.  How can this be done with the current extension? Or should it be a new feature.

**Comment by AlanWong-MS** [comment]
Related: #56

It will be a new feature; currently, we don't have resources allocated to the task but we would be more than happy to take contributions. Closing this thread to consolidate everyone's proposals in the linked thread.
