### ISSUE TITLE
Generated code does not compile when configuring an OdataConnectedService

### ISSUE THREAD

**Issue by raz-sinay** [OData/lab#80]
When createing an OdataConnectedService using the extension (from visual studio 2017 enterprise marketplace), the generated code does not compile and outputs the error :

> Error	CS0234	The type or namespace name 'EdmxReader' does not exist in the namespace 'Microsoft.OData.Edm.Csdl' (are you missing an assembly reference?)

Problematic code :

`[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]`
            `private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()`
`            {`
               ` global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);`
`                try`
`                {                    `
`                    return global::Microsoft.OData.Edm.Csdl.EdmxReader.Parse(reader);`
 `               }`
  `              finally`
   `             {`
    `                ((global::System.IDisposable)(reader)).Dispose();`
     `           }`
      `      }`

The type EdmxReader should be replaced with CsdlReader as referenced in [issue#632](https://github.com/OData/odata.net/issues/632)

**Comment by unchase** [comment]
You can try [Unchase OData ConnectedService](https://marketplace.visualstudio.com/items?itemName=Unchase.unchaseodataconnectedservice) for checking this issue.

**Comment by habbes** [comment]
Hi @raz-sinay The latest release of OData Connected Service on VS Marketplace fixes this issue: https://marketplace.visualstudio.com/items?itemName=laylaliu.ODataConnectedService
