### ISSUE TITLE
Need Auth support

### ISSUE THREAD

**Issue by SteveLasker** [OData/lab#9]
When trying to add the SAP OData feed, it failed as I was never given an opportunity to authenticate.
Auth support needs to support the providers auth pattern. SAP has a few styles, including basic auth. 
![odataauthsupport](https://cloud.githubusercontent.com/assets/7647382/8236684/d1bc40c8-159e-11e5-8966-b7fa7a10694a.png)

**Comment by LaylaLiu** [comment]
About Auth, user can always download the $metadata to their local machine, and generate client proxy file against that machine.
So the priority for this issue is not high. I will just close this one. If you have any different idea, please add a comment and reopen this issue.

**Comment by duhowise** [comment]
What if they are provided with a choice to enter username(maybe in a tab or window), password and domain which is then used for scaffolding? Depending on your level of experience, downloading the metadata and generating code against it may be too much of a laborious process.
