### ISSUE TITLE
[Connected Service] Set the max protocol version of the generated client

### ISSUE THREAD

**Issue by groovyfeng** [OData/lab#91]
To set the max protocol version of the generated client, the version need to passed in to the constructor of DataServiceContext:
`public DataServiceContext(Uri serviceRoot, DataServiceProtocolVersion maxProtocolVersion);`

However, the generated client code only uses the constructor without it:
`public AccountServiceClient(global::System.Uri serviceRoot) : 
        base(serviceRoot) `

There is no way for us to change the max protocol version with the generated code. Could we have the code generator to add a client constructor that takes the max protocol version as a parameter? Like:
`public AccountServiceClient(global::System.Uri serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion) : 
        base(serviceRoot, maxProtocolVersion) `

Thanks

**Comment by chuanboz** [comment]
that will be the same issue for OData v4 generated client, in additional to the old v3 clients.

**Comment by groovyfeng** [comment]
The generated client will call the right constructor and set the DataServiceProtocolVersion to V3 if EDMX specifies the MaxDataServiceVersion attribute.
<edmx:DataServices m:DataServiceVersion="3.0" m:MaxDataServiceVersion="3.0" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
