### ISSUE TITLE
Allow Connected Service to generate types as internal

### ISSUE THREAD

**Issue by Danthar** [OData/lab#93]
When using multiple libraries which use an OData connected service. Their service types are exposed as public. This causes issues when using multiple libraries which use the same odata endpoint, in the same application.

This problem can be mitigated by using custom namespace prefixes during generation of the OData reference.

But what would be ideal is that these service types can be marked as internal.

**Comment by KanishManuja-MS** [comment]
@odero Another worthwhile ask.

**Comment by unchase** [comment]
Add this feature in [Unchase.Odata.Connectedservice v1.4.0](https://github.com/unchase/Unchase.Odata.Connectedservice/releases/tag/v1.4.0)
- Only for OData v4 and with unchecked `Add code templates (Whether to include the T4 files into this project)` option.

[Marketplace](https://marketplace.visualstudio.com/items?itemName=Unchase.unchaseodataconnectedservice)

**Comment by habbes** [comment]
@Danthar this feature is available in the latest release of OData Connected Service available on the marketplace: https://marketplace.visualstudio.com/items?itemName=laylaliu.ODataConnectedService
