### ISSUE TITLE
Support for Visual Studio 2019

### ISSUE THREAD

**Issue by dotnetero** [OData/lab#94]
On Visual Studio 2019, can´t add Connected Service. 
Have thought to be compatible ?

Thanks...

**Comment by unchase** [comment]
You can try my [Unchase OData ConnectedService](https://marketplace.visualstudio.com/items?itemName=Unchase.unchaseodataconnectedservice) for solve this problem.

**Comment by marciooliveiraprimaverabss** [comment]
@unchase Your solution can't update it.

**Comment by unchase** [comment]
> @unchase Your solution can't update it.

My connected service supports Visual Studio 2019. See **Troubleshooting** in [README](https://github.com/unchase/Unchase.Odata.Connectedservice):

## Installation completes but I can't see the Service in the list of connected services (Visual Studio 2019)
- Relevant [bug report](https://developercommunity.visualstudio.com/content/problem/468751/vs2019-preview-cannot-install-connected-service-ex.html). Connected Services will be restored in the first update to [Visual Studio](https://visualstudio.microsoft.com/vs/) 2019 (version 16.1).

So keep waiting Visual Studio 2019 16.1 Release.

**Comment by dotnetero** [comment]
Hi @unchase.

Thanks for the comment, I will have to wait for version 2019 16.1, install your version of the service, but not listed as already commented.

Thank You, Dotnetero.

**Comment by unchase** [comment]
[Unchase OData ConnectedService](https://marketplace.visualstudio.com/items?itemName=Unchase.unchaseodataconnectedservice&ssr=false#overview) starting from VisualStudio 2019 Preview v16.2.0 now work fine. Enjoy!

**Comment by habbes** [comment]
Hi @dotnetero the latest release of OData Connected Service supports both VS 2017 and 2019. It s available on VS Marketplace: https://marketplace.visualstudio.com/items?itemName=laylaliu.ODataConnectedService
