### ISSUE TITLE
Official Version of ODataConnectedService for VS2019

### ISSUE THREAD

**Issue by wurst0815** [OData/lab#97]
Hi,

will there be an official Version of the ODataConnectedService published by Microsoft that works with VS2019?

I know that there is a Version provided bv Unchase, but I would prefer a Solution provided (and maintained) by Microsoft.

Thanks

**Comment by unchase** [comment]
Hi, @wurst0815 !

As far as I can tell, Microsoft is not going to support this connected service in the future.

Why are you not happy with the version of the [Unchase OData Connected Service](https://marketplace.visualstudio.com/items?itemName=Unchase.unchaseodataconnectedservice) that I support?
If you have suggestions for improvement, you can leave your issues [here](https://github.com/unchase/Unchase.OpenAPI.Connectedservice/issues/new?title=FEATURE). I try to respond to issues in a timely manner.

**Comment by wurst0815** [comment]
Hi,

I really appreciate your efforts. I just feel a bit uncomfortable using an assembly in a productive environment that is maintained by only one single person.

**Comment by unchase** [comment]
The project I am developing is in open source. So anyone can support the project, help in its development.
Unfortunately, so far there have been no people willing to participate in the development of the project, however, this is possible, and I only welcome this.

**Comment by unchase** [comment]
In addition, I use The [Unchase OData Connected Service](https://marketplace.visualstudio.com/items?itemName=Unchase.unchaseodataconnectedservice) myself  in the product environment, which allows me to quickly correct errors that occur.
The Connected Service supported by Microsoft is developed by the same programmers, who can also make errors and create bugs. So drop your fears.

**Comment by habbes** [comment]
Hi, @wurst0815, we have a released a new version of connected service (v0.4.0) that supports VS 2019.  It's available on VS Marketplace: https://marketplace.visualstudio.com/items?itemName=laylaliu.ODataConnectedService
